version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: finances-db
    environment:
      POSTGRES_DB: financespro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/create-test-database.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - finances-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finances-backend-prod
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgres://postgres:password@db:5432/financespro
      - JWT_SECRET=finances-pro-suisse-secret-key-production
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - finances-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.finance.event-connect.app`)"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: finances-frontend-prod
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=https://api.finance.event-connect.app
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - finances-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`finance.event-connect.app`)"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

volumes:
  postgres_data:
    driver: local

networks:
  finances-network:
    driver: bridge