version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: finances-backend-prod
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgres://postgres:lYPS50GDgjiA6QEL0GG0qHefqqGcGo8I2njYiBkpxlSuuhMv8Lpv1K2VY@91.107.237.159:5432/db_finance
      - JWT_SECRET=finances-pro-suisse-secret-key-production
    volumes:
      - backend_data:/app/data
    restart: unless-stopped
    networks:
      - finances-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.finance.event-connect.app`)"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: finances-frontend-prod
    ports:
      - "8080:80"
    environment:
      - REACT_APP_API_URL=https://api.finance.event-connect.app
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - finances-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`finance.event-connect.app`)"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

volumes:
  backend_data:
    driver: local

networks:
  finances-network:
    driver: bridge
  coolify:
    external: true